Ft signup 159965437
andela/ah-leagueOfLegends-frontend pull request #10
Opened 2018-10-10 14:34 UTC by Mutuba

## What does this PR do?
```
Implements sign up page for Authors Haven.
```

## Description of Task to be completed?
```
Users should be able to create an account by passing appropriate parameters.

```

## How should this be manually tested?

```
Clone the repo. cd into ah-leagueoflegends-frontend. npm install. Go to the browser. Click on Getting Started button. A register pops up. Enter your details and click on register.

```
## Any background context you want to provide?

```
Authors Haven did not have front end sign up functionality.

```

## What are the relevant pivotal tracker stories?

[#159965437](https://www.pivotaltracker.com/story/show/159965437)

## Screenshots if available to support PR.

<img width="1160" alt="screen shot 2018-10-10 at 17 31 52" src="https://user-images.githubusercontent.com/39365725/46743643-2f067f00-ccb2-11e8-8baf-359b45edbbf6.png">

## Questions:

```
Can it be done better?

```

2018-10-11 16:38 UTC, Mutuba commented on src/styles/styles.scss
> +#modal2 {
A component needs an id as selector in order to render.

2018-10-11 16:39 UTC, Mutuba commented on src/styles/styles.scss
> +#modal2 {
A modal needs an id in order to be selected so as to be rendered.

2018-10-11 16:40 UTC, Mutuba commented on src/components/Authentication/Signup/Register.js
> +import React, { Component } from 'react';
Component has been used during creation of component(Register)

2018-10-11 16:40 UTC, Mutuba commented on src/styles/scss/components/_articles.scss
> +  margin-left: 45px !important;
Needed that in order to style the aside articles.

2018-10-11 16:41 UTC, Mutuba commented on src/styles/scss/base/_settings.scss
> +$color-green: #008080;
I have put trailing new line

2018-10-11 19:19 UTC, kevintumbo requested changes

2018-10-11 19:19 UTC, kevintumbo commented on src/components/Authentication/Signup/store.js
> +export default store;
Do not create multiple stores in one project. Use the store in the stores folder instead

2018-10-11 19:19 UTC, kevintumbo commented on src/containers/Articles/Read/index.js
> +// import ArticleHeader from '../../../components/Header';
remove commented code

2018-10-11 19:19 UTC, kevintumbo commented on src/index.js
> +import './styles/styles.scss';
shouldn't this be .css?

2018-10-11 19:19 UTC, kevintumbo commented on src/styles/styles.scss
> +  text-align: center;
this can be done

2018-10-11 19:19 UTC, kevintumbo commented on src/styles/styles.scss
> +  background-color: rgb(219, 235, 235)
this too.

2018-10-11 19:19 UTC, kevintumbo commented on src/styles/styles.scss
> +  margin: 1% 25%;
this too.

2018-10-11 19:19 UTC, kevintumbo commented on src/components/Authentication/Signup/Home.js
> +// }
why do we have a whole file full of commented code?

2018-10-12 05:08 UTC, Mutuba commented on src/components/Authentication/Signup/store.js
> +export default store;
Sorry, the initial commit had that, I forgot to remove the store in the signup.  I have fixed that!

2018-10-12 05:09 UTC, Mutuba commented on src/containers/Articles/Read/index.js
> +// import ArticleHeader from '../../../components/Header';
I have done that!

2018-10-12 07:53 UTC, kevintumbo requested changes

2018-10-12 07:53 UTC, kevintumbo commented on src/store/store.js
>  const middlewares = [logger, thunk];
expose your initial state to the store.

2018-10-12 07:53 UTC, kevintumbo commented on src/styles/styles.scss
> +  text-align: center;
properties not ordered yet.

2018-10-12 07:53 UTC, kevintumbo commented on src/styles/styles.scss
> +  background-color: rgb(219, 235, 235)
this hasn't been addressed yet.

2018-10-12 07:53 UTC, kevintumbo commented on src/styles/styles.scss
> +  margin: 1% 25%;
this hasn't been addressed yet.

2018-10-12 08:50 UTC, kevintumbo approved these changes

2018-10-12 08:52 UTC, DerKip approved these changes

2018-10-12 08:55 UTC, Derrickkip approved these changes

2018-10-12 10:42 UTC, merged