Ft reset password link 159965438
andela/ah-leagueOfLegends-frontend pull request #14
Opened 2018-10-12 11:49 UTC by Teddykavooh

## What does this PR do?
```
Enables users to be presented with a reset password link, in their emails when they forget their passwords.
```

## Description of Task to be completed?
```
Create the necessary models.
Implement the password reset functionality.
Change the password reset landing page.

```

## How should this be manually tested?

```
After cloning app, start app via npm start in IDE of your choice.
Click the forgot password link, enter your email address.
Await the password reset link.

```
## What are the relevant pivotal tracker stories?

[#159965438](https://www.pivotaltracker.com/n/projects/2192365)

## Screenshots if available to support PR.

<img width="1280" alt="screen shot 2018-10-12 at 14 43 09" src="https://user-images.githubusercontent.com/39087913/46867446-a7457f80-ce2d-11e8-9227-d08c28209177.png">
<img width="1280" alt="screen shot 2018-10-12 at 14 43 14" src="https://user-images.githubusercontent.com/39087913/46867450-ac0a3380-ce2d-11e8-8701-4a63949b190d.png">
<img width="1280" alt="screen shot 2018-10-12 at 14 43 22" src="https://user-images.githubusercontent.com/39087913/46867336-533a9b00-ce2d-11e8-8e4f-06cac200aa38.png">
<img width="1280" alt="screen shot 2018-10-12 at 14 43 29" src="https://user-images.githubusercontent.com/39087913/46867349-59c91280-ce2d-11e8-8d7e-0cbc8bf49fc6.png">

2018-10-18 14:22 UTC, Quantum-35 approved these changes

2018-10-18 14:23 UTC, Mutuba approved these changes
Good work.

2018-10-18 22:38 UTC, kevintumbo approved these changes

2018-10-19 08:33 UTC, ghost approved these changes

2018-10-19 09:18 UTC, kevintumbo requested changes

2018-10-19 09:18 UTC, kevintumbo commented on src/components/Article/editor.js
> +    console.log('about to post');
remove this console.log

2018-10-19 09:26 UTC, kevintumbo approved these changes

2018-10-19 09:26 UTC, merged