[Feature #159965449] Updates styles for social sharing
andela/ah-leagueOfLegends-frontend pull request #28
Opened 2018-10-25 11:28 UTC by Mutuba

## What does this PR do?
```
Implements social sharing functionality for AuthorsHaven. Enables users to share articles via social media and email.  
```

## Description of Task to be completed?
```
Articles need to be shared via social media and email.

```

## How should this be manually tested?

```
Clone the repo leagueOfLegends-frontend. cd into ah-leagueOfLegends. Run yarn install then yarn start. On the homepage, click on signin if you have an account. Click on ReadMore on any article. You will find a share symbol that gives you options for sharing. Click on any of the options.

```
## Any background context you want to provide?

```
AuthorsHaven did not have a functionality to share articles via social media and email.

```

## What are the relevant pivotal tracker stories?

[#159965449](https://www.pivotaltracker.com/story/show/159965449)

## Screenshots if available to support PR.

<img width="939" alt="screen shot 2018-10-25 at 14 31 07" src="https://user-images.githubusercontent.com/39365725/47497261-14133d80-d862-11e8-82f5-1200846206e2.png">

2018-10-25 12:23 UTC, DerKip approved these changes

2018-10-25 12:23 UTC, Derrickkip approved these changes

2018-10-26 07:26 UTC, kevintumbo requested changes
why do you have both package-lock.json and yarn.lock
Kindly use the lock file this used by the rest of the team.

2018-10-26 07:36 UTC, kevintumbo approved these changes

2018-10-26 07:37 UTC, merged