159965445 Add pagination support for articles
andela/ah-leagueOfLegends-frontend pull request #31
Opened 2018-10-26 09:21 UTC by Quantum-35

## What does this PR do?
- Adds Pagination Support to article Landing Page.

## Description of Task to be completed?
- The user can easily navigate to previous articles using pagination.

## How should this be manually tested?
Clone the repo, cd into ah-leagueoflegends-frontend. Run **npm install** or **yarn add**. Then run yarn start.
- Start your Django backend server.
- Open the home page on your browser.
- Login
- Navigate to the home page and scroll down to navigate to previous articles.

## What are the relevant pivotal tracker stories?
[#159965445](https://www.pivotaltracker.com/story/show/159965445)

## Screenshot.
### Landing Page with pagination support.
<img width="1402" alt="screen shot 2018-10-26 at 12 20 20" src="https://user-images.githubusercontent.com/39088834/47557529-96126d80-d919-11e8-89e1-272ef44ee6c2.png">

2018-10-26 09:48 UTC, Derrickkip approved these changes

2018-10-26 10:06 UTC, Teddykavooh approved these changes

2018-10-29 14:51 UTC, kevintumbo requested changes

2018-10-29 14:51 UTC, kevintumbo commented on src/containers/Articles/Read/index.js
> +    getAllArticles(perPage, offset);
duplication function calls

2018-10-29 14:51 UTC, kevintumbo commented on src/containers/Articles/Read/index.js
> +      .catch(err => console.log(err));
remove console.log

2018-10-29 14:55 UTC, Quantum-35 commented on src/containers/Articles/Read/index.js
> +    getAllArticles(perPage, offset);
On it.

2018-10-29 14:55 UTC, Quantum-35 commented on src/containers/Articles/Read/index.js
> +      .catch(err => console.log(err));
On it.

2018-10-31 11:15 UTC, kevintumbo approved these changes

2018-10-31 11:15 UTC, merged