#159965443 Implement article rating feedback. Represent average rate using stars.
andela/ah-leagueOfLegends-frontend pull request #34
Opened 2018-10-29 11:49 UTC by Mutuba

## What does this PR do?
```
Implements feedback to enable an average rating to be represented using stars. Users can now view the popularity of an article in terms of stars.
```

## Description of Task to be completed?
```
Enable users to view the popularity of an article using stars. Separate average ratings from user's ratings.

```

## How should this be manually tested?

```

Clone the repo ah-leagueOfLegends-frontend. cd into ah-leagueOfLegends-frontend and run npm install. Sign up if you do not have an account and sign in if you have an account. On home page, click on read more. Rate an article by clicking on any number of stars.

```
## Any background context you want to provide?

```
Users could see the popularity of an article using numeric values.

```

## What are the relevant pivotal tracker stories?

[#159965443](https://www.pivotaltracker.com/story/show/159965443
## Screenshots if available to support PR.

<img width="914" alt="screen shot 2018-10-29 at 14 33 11" src="https://user-images.githubusercontent.com/39365725/47647964-ab8dce80-db89-11e8-818b-460d7da450fc.png">

## Questions:

2018-10-29 11:52 UTC, Derrickkip approved these changes

2018-10-29 12:09 UTC, Quantum-35 approved these changes

2018-10-29 12:20 UTC, DerKip approved these changes

2018-10-29 15:00 UTC, kevintumbo requested changes

2018-10-29 15:00 UTC, kevintumbo commented on src/components/Rating/Rating.js
> +                // changeRating={this.handleStarClick}
remove commented call

2018-10-29 15:00 UTC, kevintumbo commented on src/components/Rating/Rating.js
> +  // InitialRate: PropTypes.func.isRequired,
remove commented code

2018-10-29 15:00 UTC, kevintumbo commented on src/components/Rating/UserRating.js
> +    this.handleStarClick = this.handleStarClick.bind(this);
if you are using an arrow function then there is no need for using bind.

2018-10-29 15:00 UTC, kevintumbo commented on src/components/Rating/UserRating.js
> +            {/* {console.log('Current rate', this.props.ratingReducer)} */}
remove commented out code

2018-10-29 15:00 UTC, kevintumbo commented on src/containers/Articles/Article/largArticle.js
> +const mapDispatchToProps = dispatch => bindActionCreators({ fetchOneArticles: fetchArticles }, dispatch);
fix this max length error

2018-10-30 07:32 UTC, Mutuba commented on src/components/Rating/UserRating.js
> +    this.handleStarClick = this.handleStarClick.bind(this);
Thank you for advice.

2018-10-30 07:34 UTC, Mutuba commented on src/components/Rating/UserRating.js
> +            {/* {console.log('Current rate', this.props.ratingReducer)} */}
done

2018-10-30 07:34 UTC, Mutuba commented on src/components/Rating/Rating.js
> +  // InitialRate: PropTypes.func.isRequired,
done

2018-10-31 07:46 UTC, kevintumbo approved these changes

2018-10-31 07:46 UTC, merged