[Feature #159965442] Add article landing page where the first ten art…
andela/ah-leagueOfLegends-frontend pull request #8
Opened 2018-10-09 15:16 UTC by Quantum-35

## What does this PR do?
- Creates Article's Landing page.
- Creates Article header landing page.

## Description of Task to be completed?
- All articles are displayed in the article landing page, where the latest articles are displayed on top.
- Popular articles are also displayed on the right.

## How should this be manually tested?
Clone the repo, cd into ah-leagueoflegends-frontend. Run **npm install** or **yarn add**. Then run yarn start.
- Start your Django backend server.
- Open the home page on your browser.

## What are the relevant pivotal tracker stories?
[#159965442](https://www.pivotaltracker.com/story/show/159965442)

## Screenshot.
<img width="1433" alt="screen shot 2018-10-09 at 18 15 35" src="https://user-images.githubusercontent.com/39088834/46679305-5ba59280-cbef-11e8-9b8e-d5cd0509dc19.png">

2018-10-10 14:36 UTC, Derrickkip approved these changes
Looks Good To Me

2018-10-10 15:21 UTC, kevintumbo commented on src/App.js
> +  componentDidMount() {}
why do you have an empty lifecycle method?

2018-10-10 15:21 UTC, kevintumbo commented on src/components/Header/index.js
> +
same as above.

2018-10-10 15:22 UTC, kevintumbo commented on src/containers/Articles/Create/index.js
> +
same as above.

2018-10-10 15:47 UTC, Quantum-35 commented on src/containers/Articles/Create/index.js
> +
Resolved.

2018-10-10 15:48 UTC, Quantum-35 commented on src/App.js
> +  componentDidMount() {}
Because it was throwing an error that <App/> should be a pure function.

2018-10-10 15:54 UTC, kevintumbo requested changes

2018-10-10 15:54 UTC, kevintumbo commented on src/containers/Articles/Read/index.js
> +          }
create separate components for the cards that way you can easily import them and use them in one line instead of cluttering the file.
will make your code easily readable

2018-10-10 15:54 UTC, kevintumbo commented on src/styles/scss/components/_articles.scss
> +
avoid such spaces in your stylesheet

2018-10-10 15:54 UTC, kevintumbo commented on src/styles/scss/components/_articles.scss
> +
as above

2018-10-10 15:54 UTC, kevintumbo commented on src/styles/scss/components/_articles.scss
> +
as above... at this rate, I'll leave so many as above's 😄

2018-10-10 15:59 UTC, Quantum-35 commented on src/App.js
> +  componentDidMount() {}
Hello @kevintumbo If remove that lifecycle hound throws a violation that  it should be a Pure function. That is why I added that empty life cycle to remove that violation. Should I remove it?

2018-10-10 16:00 UTC, Quantum-35 commented on src/components/Header/index.js
> +
Same here. It throws a violation that I should change it to a pure function.

2018-10-10 16:00 UTC, Quantum-35 commented on src/styles/scss/components/_articles.scss
> +
Noted.

2018-10-10 16:02 UTC, Quantum-35 commented on src/styles/scss/components/_articles.scss
> +
Those spaces were specification from hound. It was throwing an error that there should be one space.
Specific error -  `Rule declaration should be followed by an empty line`

2018-10-10 16:46 UTC, Quantum-35 commented on src/containers/Articles/Read/index.js
> +          }
Noted.

2018-10-10 17:52 UTC, DerKip approved these changes

2018-10-10 20:06 UTC, Quantum-35 commented on src/containers/Articles/Read/index.js
> +          }
Done

2018-10-11 06:08 UTC, Mutuba approved these changes
Looks good!

2018-10-11 07:00 UTC, kevintumbo approved these changes

2018-10-11 07:01 UTC, merged